sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "deepali-arvind-github" # the key of the org you chose at step #3
    token:
      secure: 081e2012239f75d61242a6d1d6605f0ee29dc019 # encrypted value of your token   
 
language: node_js
node_js:
  - "8"

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --save del 
  - npm install --global gulp --save
  - gem install sass
           
script: 
  - gulp test
  - gulp build
  - cd dist && npm pack
  - mv amexio-ng-extensions-*.tgz amexio-ng-extensions.tgz
 
after_success: 
  - cd ../
  - git clone https://github.com/meta-magic/canvas-amexio-io-tar.git 
  - cd canvas-amexio-io-tar
  - cp -rf ../dist/amexio-ng-extensions.tgz .
  - git add amexio-ng-extensions.tgz 
  - git commit -m "date"
  - git push --force --quiet "https://deepali-arvind:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git" HEAD:master 
  - gulp coveralls
  - codecov

cache:
  yarn: true
